export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_RFOM_CART = "REMOVE_RFOM_CART";

export const GET_CONTENT = "GET_CONTENT"
export const ADD_CONTENT = "ADD_CONTENT"
export const UPDATE_CONTENT = "UPDATE_CONTENT"
export const DELETE_CONTENT = "DELETE_CONTENT"

export const ADDTOHISTORY = "ADDTOHISTORY"
export const REMOVEFROMHISTORY = "REMOVEFROMHISTORY"